language: python

sudo: false

matrix:
  include:
      python: 3.7
      dist: bionic
      sudo: true

install: 
  - pip install -U setuptools pip wheel
  - pip install -r src/tests/requirements.txt
  - pip install ./src

script:
  - tox
